// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DateConversion.Models;

public partial class DateRecord
{
    public int Id { get; set; }

    public DateTime? OriginalDate { get; set; }

    public string DiffDate { get; set; }
}