// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace DateConversion.Models;

public partial class DateRecordContext : DbContext
{
    public DateRecordContext()
    {
    }

    public DateRecordContext(DbContextOptions<DateRecordContext> options)
        : base(options)
    {
    }

    public virtual DbSet<DateRecord> DateRecords { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see https://go.microsoft.com/fwlink/?LinkId=723263.
        => optionsBuilder.UseSqlServer("Data Source=PC_4176\\MSSQLSERVER01;Initial Catalog=DateRecord; Trust Server Certificate=True; User ID=sasa;Password=123");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<DateRecord>(entity =>
        {
            entity.ToTable("DateRecord");

            entity.Property(e => e.OriginalDate).HasColumnType("datetime");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}